version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-competence
    restart: always
    environment:
      MYSQL_DATABASE: competence_db
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "8000:80"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: competence-app
    depends_on:
      - mysql-db
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/competence_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  mysql_data:
